import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { approvedSkills, commandLayouts, parseArgs, parseFrontmatter, repoRoot, type CommandLayoutKind } from "./lib";

const root = repoRoot();
const args = parseArgs(process.argv.slice(2));
const check = args.check === true;
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "sts-dist-"));
const out = path.join(temp, "dist");

const skillLayouts: Record<string, string> = {
  agents: ".agents/skills",
  pi: ".pi/skills",
  codex: ".codex/skills",
  claude: ".claude/skills",
  cursor: ".cursor/skills",
  opencode: ".opencode/skills",
  gemini: ".gemini/skills",
  copilot: ".github/skills"
};

for (const [target, skillRoot] of Object.entries(skillLayouts)) {
  for (const skill of approvedSkills) {
    const source = path.join(root, "skills", "core", skill);
    const dest = path.join(out, target, skillRoot, skill);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.cpSync(source, dest, { recursive: true });
  }
}

type SourceCommand = {
  sourcePath: string;
  relativePath: string;
  name: string;
  flatName: string;
  description: string;
  argumentHint: string;
  body: string;
};

function listCommandSources(dir = path.join(root, "commands"), base = path.join(root, "commands")): string[] {
  if (!fs.existsSync(dir)) return [];
  const result: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "README.md") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) result.push(...listCommandSources(full, base));
    else if (entry.name.endsWith(".md")) result.push(path.relative(base, full));
  }
  return result.sort();
}

function readCommand(relativePath: string): SourceCommand {
  const sourcePath = path.join(root, "commands", relativePath);
  const content = fs.readFileSync(sourcePath, "utf8");
  const frontmatter = parseFrontmatter(content);
  if (!frontmatter) throw new Error(`Command missing frontmatter: ${relativePath}`);
  const name = frontmatter.data.name;
  if (!name) throw new Error(`Command missing name: ${relativePath}`);
  return {
    sourcePath,
    relativePath,
    name,
    flatName: name.replace(/:/g, "-"),
    description: frontmatter.data.description ?? "Spec-to-Ship command",
    argumentHint: frontmatter.data["argument-hint"] ?? "[args]",
    body: frontmatter.body.trim() + "\n",
  };
}

function commandRelativePath(command: SourceCommand, kind: CommandLayoutKind): string {
  if (kind === "markdown-namespaced" || kind === "gemini-toml") {
    const parts = command.name.split(":");
    return path.join(...parts) + (kind === "gemini-toml" ? ".toml" : ".md");
  }
  if (kind === "copilot-prompt") return `${command.flatName}.prompt.md`;
  return `${command.flatName}.md`;
}

function markdownCommand(command: SourceCommand, kind: CommandLayoutKind): string {
  const displayName = kind === "markdown-namespaced" ? `/${command.name}` : `/${command.flatName}`;
  const alias = command.name === command.flatName ? "" : `\n\nSTS canonical command alias: \`/${command.name}\`. This harness may expose this file as \`${displayName}\`.\n`;
  return `---\ndescription: ${command.description}\nargument-hint: "${command.argumentHint}"\npackage: spec-to-ship\nsts-command: ${command.name}\n---\n\n${command.body}${alias}`;
}

function geminiToml(command: SourceCommand): string {
  const prompt = command.body.replace(/\$ARGUMENTS/g, "{{args}}").replace(/"""/g, '\\\"\\\"\\\"');
  return `# Generated by Spec-to-Ship. Source command: /${command.name}\ndescription = ${JSON.stringify(command.description)}\nprompt = """\n${prompt}\n"""\n`;
}

function renderCommand(command: SourceCommand, kind: CommandLayoutKind): string {
  if (kind === "gemini-toml") return geminiToml(command);
  return markdownCommand(command, kind);
}

const commands = listCommandSources().map(readCommand);
for (const [target, layout] of Object.entries(commandLayouts)) {
  const commandRoot = layout.local ?? layout.global?.replace(/^~\//, "");
  if (!commandRoot) continue;
  for (const command of commands) {
    const dest = path.join(out, target, commandRoot, commandRelativePath(command, layout.kind));
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, renderCommand(command, layout.kind));
  }
}

function listFiles(dir: string, base: string = dir): string[] {
  if (!fs.existsSync(dir)) return [];
  const result: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) result.push(...listFiles(full, base));
    else result.push(path.relative(base, full));
  }
  return result.sort();
}

function sameTree(a: string, b: string): boolean {
  const filesA = listFiles(a).sort();
  const filesB = listFiles(b).sort();
  if (filesA.join("\n") !== filesB.join("\n")) return false;
  for (const file of filesA) {
    if (fs.readFileSync(path.join(a, file), "utf8") !== fs.readFileSync(path.join(b, file), "utf8")) return false;
  }
  return true;
}

const dist = path.join(root, "dist");
if (check) {
  if (!sameTree(out, dist)) {
    console.error("dist is out of date. Run bun run build:dist.");
    process.exit(1);
  }
  console.log("dist is current.");
} else {
  fs.rmSync(dist, { recursive: true, force: true });
  fs.cpSync(out, dist, { recursive: true });
  console.log("Generated dist targets.");
}
fs.rmSync(temp, { recursive: true, force: true });
